### ISSUE TITLE
Audio track slowed down on long streams

### ISSUE THREAD

**Issue by Cthalin** [Giebisch/AutomaticTwitchRecorder#2]
Hi there,
I've got a weird problem while recording long (>8h) streams. In the resulting mp4 the audio track seems to be slowed down a bit. The voice from the streamer sounds very deep that's how I first noted this. I've tried another tool which records in *.ts format and played them simultaneously and just after some seconds the *.mp4 was staying behind with the audio/video track.
I've also tried another twitch recorder that uses ffmpeg for conversion and the resulting *.mp4 was also sounding weird.
Do you have any idea what might be the cause for this? Actually looks like a problem with the conversion or the mp4 container.

**Comment by Giebisch** [comment]
This tool only starts the recording of the stream via youtube-dl and is not responsible for creating the video files. Maybe you can try posting this in the youtube-dl or ffmpeg github repositories ?

**Comment by Cthalin** [comment]
Thanks for the quick response, I'll give it a try :)
